/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:8191ef82-49f4-44a5-a2d0-d88efe5bdf77",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_LKqVKFZDD",
    "aws_user_pools_web_client_id": "shumtme6f68bv4ia097122t8m",
    "oauth": {},
    "aws_user_files_s3_bucket": "findmeacontractor21659-dev",
    "aws_user_files_s3_bucket_region": "eu-west-2"
};


export default awsmobile;
