/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:98dbacc8-54fd-4777-90fd-1c8c92d835d6",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_6LiEPVl6a",
    "aws_user_pools_web_client_id": "7n7hitrp7bd2anc3mu2ijo1b87",
    "oauth": {}
};


export default awsmobile;
